type User {
  id: ID!
  role: Role
  name: String!
  email: String!
  age: Int
  salary: Float
  status: UserStatus
}

enum UserStatus {
  ACTIVE
  INACTIVE
  BLOCKED
}

type Role {
  id: ID!
  name: String!
}
